### ISSUE TITLE
No function "read_ply"

### ISSUE THREAD

**Issue by hyf015** [bomb2peng/CASIA_3Dlighting#1]
Hi, I tried with your code but did not find the definition of function "read_ply" which has been called from multiple scripts. (for example, L10 of weightLUTexture.m, L24 of TIFS_Syn1_FaceGen.m, L9 of poseTest.m)

Can you provide the function or explain what the function outputs? Thank you.

**Comment by bomb2peng** [comment]
Hi, the "read_ply" is a function from the "toolbox_graph", which is a dependency. Please see the readme. This function reads in 3D model data in ply format.

**Comment by hyf015** [comment]
Thank you, I found the code. My mistake
